### ISSUE TITLE
Feature request: make engine path configurable

### ISSUE THREAD

**Issue by Selur** [tongyuantongyu/vs-NNVISR#4]
Would be nice if one could control where the engine files get created&loaded.

**Comment by tongyuantongyu** [comment]
Could you share why and where you are going to let the engine files go? `engines` & `timing.cache` are just cache, but due to the build speed you probably don't want them to go away. And there's plan to store them into folders unique to current GPU model & TensorRT version.

**Comment by Selur** [comment]
I usually place everything related to a specific script into a subfolder with the script name, so when I clean up, I know where stuff belongs to and where it's located.
For example, if the script is named 'test@2023-06-18_13-17.py' I would play it's content into 'j:\tmp\test@2023-06-18_13-17'. So all temporary files are in that location.
It also can speed things up quite a bit to be sure, that the temp files are located on a fast local m2 ssd, while the portable Vapoursynth can reside on a network drive.
So I would be happy if I can configure a folder where all temp files go.

**Comment by tongyuantongyu** [comment]
Supported in v1.0.0-pre4 with `engine_path` argument.
