### ISSUE TITLE
unable to load lib

### ISSUE THREAD

**Issue by hooke007** [tongyuantongyu/vs-NNVISR#5]
Tested https://github.com/tongyuantongyu/vs-NNVISR/releases/tag/v1.0.0-pre3

It seems https://github.com/tongyuantongyu/vs-NNVISR/issues/2 hasn't been fixed. So I have to manually add the PATH and then load nnvisr.
But vs still quickily crashed and I captured the last info.

![Snipaste_2023-07-09_04-45-14](https://github.com/tongyuantongyu/vs-NNVISR/assets/41094733/d6606263-522c-4b20-8958-d644ca9796b8)

**Comment by tongyuantongyu** [comment]
#2 should definitely be fixed in 1.0.0-pre4. This issue is likely due to missing `zlibwapi.dll`.  The [manual install](https://github.com/tongyuantongyu/vs-NNVISR/blob/main/docs/install.md#manual-install) section is updated to include download link to it. Or follow [NVIDIA's documentation](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows).

And this is why I really prefer using some sorts of package manager, as the dependency chain is getting long.

**Comment by hooke007** [comment]
No it doesn't. The same issue (Tested 1.0.0-pre4).

![Snipaste_2023-07-09_14-43-14](https://github.com/tongyuantongyu/vs-NNVISR/assets/41094733/0f09b938-08f0-4f2b-9ffb-9b5490ecf887)

**Comment by tongyuantongyu** [comment]
Could you then try loading `nvinfer_builder_resource.dll` using https://github.com/lucasg/Dependencies or https://github.com/adamrehn/dll-diagnostics to see if it loads correctly?

And can you share what Windows 10 version your are on?

**Comment by hooke007** [comment]
win10 pro 22H2 19045.3086


![Snipaste_2023-07-09_14-52-06](https://github.com/tongyuantongyu/vs-NNVISR/assets/41094733/8e1307eb-6755-4d4f-9c3c-2a3b07d62eac)

**Comment by tongyuantongyu** [comment]
This looks weird, on my end it works correctly.

Do you have other plugins using CUDA loaded? What's your GPU model and NVIDIA driver version?

**Comment by hooke007** [comment]
> Do you have other plugins using CUDA loaded

No, only NNVISR with its deps is in the environment.
RTX4080 studio driver 536.40

**Comment by tongyuantongyu** [comment]
What's your Python and VapourSynth version? Can you test if it works in command line, or even better, if the conda distributed installation works?

**Comment by hooke007** [comment]
python 3.11.4 vs R63

Hmm...Sry I don't use conda.

**Comment by hooke007** [comment]
Well, unless adding the dir into user variable's PATH, other solutions did no help.
And then I meet with the next problem...

<img width=500 src="https://github.com/tongyuantongyu/vs-NNVISR/assets/41094733/9406aa89-b14c-4d8a-8dab-963ff4ae1df2">

The source clips' res are 1280x720 & 1920x1080
<img width=500 src="https://github.com/tongyuantongyu/vs-NNVISR/assets/41094733/c78ecbc5-1630-4470-a8a3-d0adb5be9e81">

**Comment by tongyuantongyu** [comment]
OK I see. It's vapoursynth's way of placing dependencies alongside plugin not conforming with default Windows library loading behavior.  A fix will be available later.

**Comment by tongyuantongyu** [comment]
> And then I meet with the next problem...

Looks like you are having debug output enabled. The message amount will be overwhelming. Can you check the last non-debug messages before the error?

**Comment by hooke007** [comment]
Never mind, it looks like a odd bug. It works well after restarting my device.

**Comment by tongyuantongyu** [comment]
[v1.0.0-pre5](https://github.com/tongyuantongyu/vs-NNVISR/releases/tag/v1.0.0-pre5) is released which should really address this issue.

My environment has TensorRT and cuDNN under PATH for convenience, so didn't found the issue at first place. Sorry for the confusion.
