### ISSUE TITLE
Fatal error: Cannot create infer builder

### ISSUE THREAD

**Issue by sdml0** [tongyuantongyu/vs-NNVISR#7]
I put vs-nnvisr.trt10.dll and contents of deps.windows.trt10.0.7z into one folder. When I try to use it I get "VapourSynth encountered a fatal error: Cannot create infer builder" What am I missing?
By assembling everithing for trt8 in one folder I've got: Property read unsuccessful due to missing key but no error output: _DurationNum.
vs-mlrt works fine in the same environment.
And is it no settings for trtexec?

**Comment by tongyuantongyu** [comment]
For the first issue, please provide more information by enable debug logging and share the output. You can add the following lines at the beginning of your script to get debug log:

```python
def log_debug(typ, msg):
    if typ == 0:
        print(f"Debug: {msg}")
core.add_log_handler(log_debug)
```

Also, TensorRT 10 only supports Volta or newer GPUs (that is, at least 20 series for GeForce).

<hr>

For the second issue, `_DurationNum` should be set by the source filter and always be there. Can you share the following?
- Your processing script
- Your VapourSynth, and source filter version
- Your video file, or MediaInfo output of your video file

**Comment by sdml0** [comment]
vpy  [INFO]: VapourSynth Core R66
vpy  [WARN]: NNVISR: input color primaries unspecified. Assuming default (BT.709).
vpy  [WARN]: NNVISR: input transfer characteristic unspecified. Assuming default (BT.709).
vpy  [INFO]: NNVISR: building engine for current resolution. This will take some time.
vpy  [DEBU]: [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 8511, GPU 4432 (MiB)
vpy  [DEBU]: Trying to load shared library nvinfer_builder_resource_10.dll
vpy  [DEBU]: Loaded shared library nvinfer_builder_resource_10.dll
vpy  [WARN]: 2: [builder.cpp::nvinfer1::builder::createCaskKernelLibraryImpl::152] Error Code 2: Internal Error (Assertion validateCaskKLibSize(buffer.size) failed. )
vpy  [FLAW]: Cannot create infer builder
VapourSynth encountered a fatal error: Cannot create infer builder

**Comment by sdml0** [comment]
Aaa.... model_path != models, model_path must contain folder models.
trt8 issue resolved.
Nefarious NVencC hides messages from vpy, shows only errors.

**Comment by sdml0** [comment]
When I launch vs-nnvisr.trt10.dll from vs-mlrt's vsmlrt-cuda folder it works!!!
