### ISSUE TITLE
help！！！

### ISSUE THREAD

**Issue by 84378996** [tongyuantongyu/vs-NNVISR#8]
大哥，有中文的md吗？介绍内容翻译过后能看个大概，但推敲细节时还得是看原文，奈何英文实在是菜。

**Comment by Ostrichbeta** [comment]
No worry, practice your English hard, and one day you will understand.
菜就多練

**Comment by tongyuantongyu** [comment]
There's no plan to maintain multiple versions of documentation due to the extra effort. We'll focus on improving coverage and clarity of our current documentation in English.
